[package]
name = "fm-imap"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
async-imap.workspace = true
base64.workspace = true
chrono.workspace = true
fm-core = { path = "../fm-core" }
futures.workspace = true
imap-proto.workspace = true
mail-parser.workspace = true
md-5.workspace = true
rustls-pki-types.workspace = true
serde.workspace = true
serde_urlencoded.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
webpki-roots.workspace = true
