[package]
name = "fm-http"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
fm-core = { path = "../fm-core" }
fm-plugin-compat = { path = "../fm-plugin-compat" }
fm-session = { path = "../fm-session" }
fm-user = { path = "../fm-user" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true
