[package]
name = "fm-http"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
ammonia.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
chrono = { workspace = true, features = ["clock"] }
deadpool-redis.workspace = true
futures.workspace = true
fm-core = { path = "../fm-core" }
hex.workspace = true
html-escape.workspace = true
html5ever.workspace = true
fm-imap = { path = "../fm-imap" }
fm-mime = { path = "../fm-mime" }
fm-plugin-compat = { path = "../fm-plugin-compat" }
fm-session = { path = "../fm-session" }
fm-smtp = { path = "../fm-smtp" }
fm-user = { path = "../fm-user" }
idna.workspace = true
hmac.workspace = true
lettre.workspace = true
libc.workspace = true
markup5ever_rcdom.workspace = true
md-5.workspace = true
p256.workspace = true
pgp.workspace = true
rand_core.workspace = true
reqwest.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
sha1.workspace = true
sqlx.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true
zip.workspace = true

[dev-dependencies]
data-encoding.workspace = true
openssl.workspace = true
