use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum PluginAction {
    FrickmailLogin,
    FrickmailBridgeSession,
    FrickmailRegister,
    FrickmailListAccounts,
    FrickmailAddAccount,
    FrickmailUpdateAccount,
    FrickmailDeleteAccount,
    FrickmailSetPrimary,
    FrickmailSwitchAccount,
    FrickmailSetAccountPassword,
    FrickmailRequestPasswordReset,
    FrickmailResetPassword,
    FrickmailMe,
    FrickmailGetTotpStatus,
    FrickmailEnableTotp,
    FrickmailConfirmTotp,
    FrickmailDisableTotp,
    FrickmailDiscoverServices,
    FrickmailActivateService,
    FrickmailSaveOAuthToken,
    FrickmailSearch,
    FrickmailUnifiedInbox,
    FrickmailGetPrefs,
    FrickmailSetPrefs,
    FrickmailListIdentities,
    FrickmailAddIdentity,
    FrickmailDeleteIdentity,
    FrickmailSetDefaultIdentity,
    FrickmailListRules,
    FrickmailAddRule,
    FrickmailDeleteRule,
    FrickmailToggleRule,
    FrickmailApplyRules,
    FrickmailCheckNewMail,
    FrickmailLongPollNewMail,
    FrickmailGetMessageBody,
    FrickmailGetVapidKey,
    FrickmailPushSubscribe,
    FrickmailPushUnsubscribe,
    FrickmailExportMessage,
    FrickmailExportFolder,
    FrickmailImportEml,
    FrickmailListTasks,
    FrickmailAddTask,
    FrickmailCompleteTask,
    FrickmailDeleteTask,
    FrickmailUpdateTask,
    FrickmailSmimeListCerts,
    FrickmailSmimeImportP12,
    FrickmailSmimeImportCert,
    FrickmailSmimeDeleteCert,
    FrickmailSmimeSign,
    FrickmailSmimeVerify,
    FrickmailListOidcLinks,
    FrickmailUnlinkOidc,
    JsonContactsSync,
    JsonDeduplicateContacts,
    JsonAddContact,
    JsonCalendarEvents,
    JsonCalendarList,
    JsonCalendarSave,
    JsonCalendarDelete,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PluginRequest {
    pub action: String,
    #[serde(default)]
    pub payload: Value,
}

pub type PluginResponse = Value;
